version: '3.4'

services:
  restserver:
    image: restserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 2000:2000
